/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ObservationsRouteImport } from './routes/observations'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CodeRouteImport } from './routes/code'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesIndexRouteImport } from './routes/entities/index'
import { Route as DecisionsIndexRouteImport } from './routes/decisions/index'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities/$entityId'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions/$decisionId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationsRoute = ObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecisionsRoute,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => EntitiesRoute,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/$decisionId',
  path: '/$decisionId',
  getParentRoute: () => DecisionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/code': typeof CodeRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/entities': typeof EntitiesRouteWithChildren
  '/graph': typeof GraphRoute
  '/observations': typeof ObservationsRoute
  '/search': typeof SearchRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/decisions/': typeof DecisionsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/code': typeof CodeRoute
  '/graph': typeof GraphRoute
  '/observations': typeof ObservationsRoute
  '/search': typeof SearchRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/decisions': typeof DecisionsIndexRoute
  '/entities': typeof EntitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/code': typeof CodeRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/entities': typeof EntitiesRouteWithChildren
  '/graph': typeof GraphRoute
  '/observations': typeof ObservationsRoute
  '/search': typeof SearchRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/decisions/': typeof DecisionsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/code'
    | '/decisions'
    | '/entities'
    | '/graph'
    | '/observations'
    | '/search'
    | '/decisions/$decisionId'
    | '/entities/$entityId'
    | '/decisions/'
    | '/entities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/code'
    | '/graph'
    | '/observations'
    | '/search'
    | '/decisions/$decisionId'
    | '/entities/$entityId'
    | '/decisions'
    | '/entities'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/code'
    | '/decisions'
    | '/entities'
    | '/graph'
    | '/observations'
    | '/search'
    | '/decisions/$decisionId'
    | '/entities/$entityId'
    | '/decisions/'
    | '/entities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CodeRoute: typeof CodeRoute
  DecisionsRoute: typeof DecisionsRouteWithChildren
  EntitiesRoute: typeof EntitiesRouteWithChildren
  GraphRoute: typeof GraphRoute
  ObservationsRoute: typeof ObservationsRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observations': {
      id: '/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof ObservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/decisions/': {
      id: '/decisions/'
      path: '/'
      fullPath: '/decisions/'
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof DecisionsRoute
    }
  }
}

interface DecisionsRouteChildren {
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
}

const DecisionsRouteChildren: DecisionsRouteChildren = {
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
}

const DecisionsRouteWithChildren = DecisionsRoute._addFileChildren(
  DecisionsRouteChildren,
)

interface EntitiesRouteChildren {
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CodeRoute: CodeRoute,
  DecisionsRoute: DecisionsRouteWithChildren,
  EntitiesRoute: EntitiesRouteWithChildren,
  GraphRoute: GraphRoute,
  ObservationsRoute: ObservationsRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
